name: 'Initialize Bit'
description: 'Initialize Bit'
branding: 
  icon: 'download'
  color: 'purple'
inputs:
  ws-dir:
    description: "Workspace json file directory path"
    required: false
    default: './'
runs:
  using: 'composite'
  steps:
    # - name: Setup Node
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: '18.19.0'
    - name: Run Bit Initialization Script
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        WS_DIR: ${{ inputs.ws-dir }}
